# Generated by Django 4.2.29 on 2026-04-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(db_index=True, max_length=18, unique=True)),
                ("whatsapp", models.CharField(blank=True, max_length=18)),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("10-20", "₹10k–20k"),
                            ("20-40", "₹20k–40k"),
                            ("40-80", "₹40k–80k"),
                            ("80+", "₹80k+"),
                        ],
                        db_index=True,
                        default="10-20",
                        max_length=12,
                    ),
                ),
                (
                    "product_interest",
                    models.CharField(
                        choices=[
                            ("Ring", "Ring"),
                            ("Chain", "Chain"),
                            ("Earrings", "Earrings"),
                            ("Bridal Set", "Bridal Set"),
                        ],
                        db_index=True,
                        default="Ring",
                        max_length=24,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("VIP", "VIP"),
                            ("High Value", "High Value"),
                        ],
                        db_index=True,
                        default="Regular",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("Ring", "Ring"),
                            ("Chain", "Chain"),
                            ("Earrings", "Earrings"),
                            ("Bridal Set", "Bridal Set"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("Wedding", "Wedding"),
                            ("Gift", "Gift"),
                            ("Festival", "Festival"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_followup_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        db_index=True,
                        default="Pending",
                        max_length=12,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["next_followup_date"],
            },
        ),
    ]
