# Generated by Django 4.2.29 on 2026-04-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_purchase_product_to_products(apps, schema_editor):
    Purchase = apps.get_model("crm", "Purchase")
    through = Purchase.products.through
    for purchase in Purchase.objects.exclude(product_id__isnull=True).iterator():
        through.objects.get_or_create(
            purchase_id=purchase.pk,
            producttype_id=purchase.product_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0002_occasiontype_producttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="followup",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="purchases", to="crm.producttype"
            ),
        ),
        migrations.RunPython(copy_purchase_product_to_products, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="purchase",
            name="occasion",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="product",
        ),
    ]
