# Generated by Django 4.2.29 on 2026-04-02

from django.db import migrations, models


def populate_amount_range(apps, schema_editor):
    Purchase = apps.get_model("crm", "Purchase")
    for purchase in Purchase.objects.all().iterator():
        amount = purchase.amount or 0
        if amount < 10000:
            amount_range = "5000-10000"
        elif amount < 20000:
            amount_range = "10000-20000"
        elif amount < 30000:
            amount_range = "20000-30000"
        elif amount < 50000:
            amount_range = "30000-50000"
        elif amount < 100000:
            amount_range = "50000-100000"
        else:
            amount_range = "100000+"
        Purchase.objects.filter(pk=purchase.pk).update(amount_range=amount_range)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_purchase_occasion_remove_purchase_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="amount_range",
            field=models.CharField(
                choices=[
                    ("5000-10000", "Rs. 5k - 10k"),
                    ("10000-20000", "Rs. 10k - 20k"),
                    ("20000-30000", "Rs. 20k - 30k"),
                    ("30000-50000", "Rs. 30k - 50k"),
                    ("50000-100000", "Rs. 50k - 1L"),
                    ("100000+", "Rs. 1L+"),
                ],
                default="5000-10000",
                max_length=20,
            ),
        ),
        migrations.RunPython(populate_amount_range, migrations.RunPython.noop),
    ]
