# Generated by Django 4.2.29 on 2026-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_normalize_followups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="amount_range",
            field=models.CharField(
                choices=[
                    ("0-5000", "Rs. 0 - 5k"),
                    ("5000-10000", "Rs. 5k - 10k"),
                    ("10000-20000", "Rs. 10k - 20k"),
                    ("20000-30000", "Rs. 20k - 30k"),
                    ("30000-50000", "Rs. 30k - 50k"),
                    ("50000-100000", "Rs. 50k - 1L"),
                    ("100000+", "Rs. 1L+"),
                ],
                default="5000-10000",
                max_length=20,
            ),
        ),
    ]
